# flake8: noqa

"""Updated size type to int

Revision ID: 938b582999d8
Revises: b386283f4855
Create Date: 2025-11-11 11:50:30.265300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b582999d8'
down_revision: Union[str, Sequence[str], None] = 'b386283f4855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'size',
        existing_type=sa.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'size',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
